SET ECHO ON
SET LINE 300
set timing on
spool grant.log
GRANT SELECT ON SIGMA_E.MAKER_MST TO RVNNET;
GRANT SELECT ON SIGMA_E.CODE_MST TO RVNNET;
GRANT SELECT ON SIGMA_E.CATEG_MST TO RVNNET;
GRANT SELECT ON SIGMA_E.SGENS_CATEG_LST TO RVNNET;
GRANT SELECT ON COMMON.SRUSID TO RVNNET;
GRANT SELECT ON COMBOM.SSGRDA TO RVNNET;
GRANT SELECT ON COMBOM.SSGBPN TO RVNNET;
GRANT SELECT ON COMBOM.SSGRKI TO RVNNET;
GRANT SELECT ON PROJECTC.PTKM TO RVNNET;
GRANT SELECT ON SPERC.M_DA TO RVNNET;
GRANT SELECT ON SPERC.PN_MST TO RVNNET;
GRANT SELECT ON SPERC.DRAWINGLIST TO RVNNET;
GRANT SELECT ON SPERC.ECI_TBL TO RVNNET;
GRANT SELECT ON SPERC.DIEDRAWING_TBL TO RVNNET;
GRANT SELECT ON SPERC.KISYU_DISTRIB_TBL TO RVNNET;
GRANT SELECT ON SPERC.DISTRIB_TBL TO RVNNET;
GRANT SELECT ON SPERC.REFLECTKISYU_TBL TO RVNNET;
GRANT SELECT ON STAR.SNMP TO RVNNET;
GRANT SELECT ON STAR.SNFL TO RVNNET;
GRANT SELECT ON STAR.TNTO TO RVNNET;
GRANT SELECT ON STAR.GTFL TO RVNNET;
GRANT SELECT ON COMMON.AJINMST TO RVNNET;
GRANT SELECT ON COMMON.SIRCNV TO RVNNET;
GRANT SELECT ON COMMON.RGSRFL TO RVNNET;
spool off
exit
